name: "Codecheck"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Check formatting with ruff
      run: |
        pip install ruff
        ruff format
        ruff check --fix
        ruff check
