name: "Codecheck"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Check formatting with ruff
      run: |
        pip install ruff
        ruff format
        ruff check --fix
        ruff check

    - name: Commit and push if ruff makes changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A
        git commit -m "Apply ruff formatting" -a || true  # This will not fail if there's nothing to commit
        git push --set-upstream origin HEAD:${{ github.head_ref }} --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
