name: "Codecheck"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Check formatting with ruff
      run: |
        pip install ruff
        ruff format
        ruff check --fix
        ruff check

    - name: Commit and push if ruff makes changes
      run: |
        git config --global user.email "magnusvinjebo@hotmail.com"
        git config --global user.name "Magdk01"
        git add -A
        git commit -m "Apply ruff formatting" || true  # This will not fail if there's nothing to commit
        git push --set-upstream origin HEAD:${{ github.head_ref }}
